name: point_glass
description: "A Flutter package for 3D point cloud visualization with interactive grid, axis, polygons, and annual sectors."
version: 0.0.1
homepage: https://github.com/immsong/point_glass
repository: https://github.com/immsong/point_glass
issue_tracker: https://github.com/immsong/point_glass/issues
documentation: https://github.com/immsong/point_glass#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # Add assets used in the package here
